//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.30 at 09:05:19 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.discoveryassignment.com/xml/routes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_discoveryassignment_com.xml.routes;
